# Generated by Django 4.0.3 on 2022-03-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddedWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addedword', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddedWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userword', models.JSONField()),
            ],
        ),
    ]
