# Generated by Django 4.0.3 on 2022-03-12 20:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('wordly_app', '0002_gameid_useraddedword_game'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='addedword',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
