# Generated by Django 4.0.3 on 2022-03-12 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordly_app', '0003_alter_addedword_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='addedword',
            managers=[
            ],
        ),
    ]
