# Generated by Django 4.0.3 on 2022-03-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordly_app', '0004_alter_addedword_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameid',
            name='mord_guess_list',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameid',
            name='game_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
